name: "🚀 Fix Report"
description: "버그 수정이나 개선 사항을 기록하는 템플릿"
title: "fix: "
body:
  - type: input
    attributes:
      label: 🔗 관련 이슈
      description: "이 Fix가 해결한 기존 이슈가 있다면 추가해주세요. (ex. #123)"
    validations:
      required: false
  - type: textarea
    attributes:
      label: 🛠 수정 내용
      description: 어떤 문제가 수정되었는지 설명해주세요.
      placeholder: 어떤 버그를 해결했는지 적어주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업 내역
      description: 작업한 내용을 체크박스 형태로 정리해주세요.
      placeholder: |
        <ex. 예시 지문>
        - [ ] <체크 1>
        - [ ] <체크 2>
      value: |
        - [ ] <#이슈 1> <작업 내용>
        - [ ] <#이슈 1> <작업 내용>
        - [ ] <#이슈 1> <작업 내용>
        - [ ] 더입력 ...
      render: ''
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙋🏻 리뷰 요구사항 (선택)
      description: 코드 리뷰 요청이 필요한 부분을 작성해주세요.
      placeholder: |
        - 기존 코드와 비교해서 변경된 부분의 논리적 타당성을 봐주세요.
        - 리팩토링할 수 있는 여지가 있는지 피드백 부탁드립니다.
        - 테스트 커버리지가 충분한지 확인해 주세요.
    validations:
      required: false
