name: Java CI with Gradle

on:
  pull_request:
    branches: [ "backend/**", "backend/feature/**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew

      - name: Create application.yml from GitHub Secrets
        run: |
          mkdir -p backend/src/main/resources
          echo "${{ secrets.APPLICATION }}" | base64 --decode > backend/src/main/resources/application.yml

      - name: Build with Gradle Wrapper
        working-directory: backend
        run: ./gradlew build